base.py: changes find_pn() so it returns PN instead of PATH
The value returned by find_pn() is now a package name instead of a path, making
it more usable along the test suite.

For instance, take the following:
All test cases using tinfoil.parse_recipe() for parsing and retrieving metadata
must know the PN in order to work properly, but a PATH was provided by find_pn()
instead. Referring to the tinfoil API, parse_recipe() takes ONLY the package
name (PN) as input, failing and raising an exception otherwise.

This change allows the test suite to be ran correctly and avoids the
bb.exceptions that had been caught in the past as a result of executing metadata
test cases.

$ patchtest <patch> <repo> <suite>

Traceback (most recent call last):
  File "/home/dplascen/bin/patchtest", line 152, in _runner
    result = runner.run(suite)
...
  File "/usr/lib/python3.4/traceback.py", line 125, in _iter_chain
    context = exc.__context__
AttributeError: 'NoneType' object has no attribute '__context__'
None
patchtest: something went wrong
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/suite.py", line 166, in _handleClassSetUp
    setUpClass()
...
  File "/home/dplascen/repos/patchtest/openembedded-core/bitbake/lib/bb/main.py",
    line 473, in setup_bitbake
    bb.fatal("Unable to connect to bitbake server, or start one")
  File "/home/dplascen/repos/patchtest/openembedded-core/bitbake/lib/bb/__init__.py",
  line 104, in fatal
    raise BBHandledException()
bb.BBHandledException
None

Signed-off-by: Daniela Plascencia <daniela.plascencia@linux.intel.com>